---
- hosts: all
  sudo: yes
  tasks:
    - name: install git
      apt: name=git update_cache=yes
    - name: run docker install script
      script: docker.sh
    - name: run node install script
      script: npm.sh
    - name: install node
      apt: name=nodejs
    - name: pull meneal/buildbox
      command: docker pull meneal/buildbox
    - name: install software properties common
      apt: name=software-properties-common update_cache=yes
    - name: add ansible repo
      apt_repository: repo='ppa:ansible/ansible' 
    - name: install ansible
      apt: name=ansible 
    - name: install pip
      apt: name=python-pip
    - name: install dopy
      command: pip install dopy
    - name: install ruby gems
      apt: ruby-full
    - name: install tugboat
      command: gem install tugboat
    #- name: Server Going Up
      #command: node server.js >> somelog.txt chdir=data/

